### ISSUE TITLE
Error running logger

### ISSUE THREAD

**Issue by ne4u** [resurfaceio/logger-lua#3]
This is the error I get after installing with luarocks and configuring openresty with the example:

```
2022/10/22 20:37:00 [error] 328#328: *9 failed to run body_filter_by_lua*: ...ocal/share/lua/5.1/usagelogger/http_logger_for_nginx.lua:25: bad argument #1 to 'pairs' (table expected, got string)
stack traceback:
	[C]: in function 'pairs'
	...ocal/share/lua/5.1/usagelogger/http_logger_for_nginx.lua:25: in function 'bodyfilter'
	body_filter_by_lua:3: in main chunk while sending to client, client: 10.######, server: demo.######.com, request: "GET /?test=value HTTP/2.0", upstream: "https://origin/?test=value", host: "demo.######app"
2022/10/22 20:37:00 [error] 328#328: *11 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/usagelogger/http_message.lua:11: request required
stack traceback:
coroutine 0:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/usagelogger/http_message.lua:11: in function 'send'
	...ocal/share/lua/5.1/usagelogger/http_logger_for_nginx.lua:46: in function <...ocal/share/lua/5.1/usagelogger/http_logger_for_nginx.lua:41>, context: ngx.timer, client: 10.######, server: 0.0.0.0:443
```

**Comment by ne4u** [comment]
The same error occurs with the Resurface container:  https://github.com/resurfaceio/test-openresty

**Comment by ne4u** [comment]
reverting to 2.0-0 only fixes the first error in bodyfilter.  the second error still remains.

**Comment by ne4u** [comment]
further testing shows that ngx.ctx.req and ngx.ctx.res are nil

**Comment by monrax** [comment]
Hi there @ne4u, thank you for taking the time to open this issue. I saw it earlier today but it was just now that I was able to reply.

I believe the issue had to do with two main things in `usagelogger/http_logger_for_nginx.lua`: not parsing the `qs` query string into a table and not initializing the `req.params` table before attempting to index a key. With those two things fixed, I made a new release `2.1.1-1`in order to test it with [`resurfaceio/test-openresty`]( https://github.com/resurfaceio/test-openresty), and it works! (on my end at least). Could you try installing the latest version of this package and running the example test again, please?

The dockerfile in that repo needs to be modified that so that a whole new release is not required just to test a specific commit, tag or branch of this one. That and writing more unit tests are priorities for this logger.

**Comment by ne4u** [comment]
Thanks!  I can confirm the 2nd error persists.  It took either several tries or several minutes to get the error though. That could be why you didn't notice it.  But before I got the error, I noticed that no data was being sent by doing packet captures.  Here's the same error with the updated line numbers:

```
2022/10/25 02:24:49 [error] 7#7: *4 lua entry thread aborted: runtime error: ...nresty/luajit/share/lua/5.1/usagelogger/http_message.lua:11: request required
stack traceback:

coroutine 0:
    [C]: in function 'assert'
    ...nresty/luajit/share/lua/5.1/usagelogger/http_message.lua:11: in function 'send'
    ...ajit/share/lua/5.1/usagelogger/http_logger_for_nginx.lua:69: in function <...ajit/share/lua/5.1/usagelogger/http_logger_for_nginx.lua:64>, context: ngx.timer, client: 10.###.###.###, server: 0.0.0.0:80
```
    
Again it seems that ngx.ctx.req and ngx.ctx.res are nil.  I verified by altering http_logger_for_nginx.lua to write to nginx error.log if they are nil and not call ngx.timer.at()

Hopefully, that helps.

**Comment by ne4u** [comment]
Part of my problem not seeing the traffic with tcpdump was due to not specifying a resolver in nginx when using a FQDN for the logger url.  When adding a resolver I see the traffic.  However, the POST is nil since the res and req are nil as previously noted.

**Comment by ne4u** [comment]
error due to environment conf

**Comment by monrax** [comment]
Hi @ne4u! I'm just seeing your updates —is the 2nd error still showing up for you? If it isn't anymore after modifying your env config, could you share what was it that you changed? I'd like to provide better error handling for cases like that (at least provide more useful error messages)

**Comment by ne4u** [comment]
i'm not sure what exactly i changed that fixed the issue.  I do know that adding the resolver directive helped.  but i also know that shouldn't have impacted the nil value I know was coming from res and req variables.  As I noted I added debug logging to validate that they where nil.  I do have some quite complete ngnix configurations that I suspect may have been the culprit.  After stripping the configs to a bare minimum things started working. now nginx/openresty is strickly a reverse proxy.

I'm not sure if it makes sense for Resurface platform.  However, it does make sense to me to include some additional details about the request which i'm putting in body_filter_by_lua_block:

ngx.ctx.res.headers['Connnection-ID'] = ngx.var.connection
ngx.ctx.res.headers['Request-Count'] = ngx.var.connection_requests
ngx.ctx.res.headers['Pipelining'] = ngx.var.pipe
ngx.ctx.res.headers['Client-Address'] = ngx.var.remote_addr
ngx.ctx.res.headers['Request-URI'] = ngx.var.request_uri
ngx.ctx.res.headers['Query-String'] = ngx.var.query_string

From a security and ML perspective that data seems relevant.
